version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always

  backend:
    dns:
      - 8.8.8.8
      - 1.1.1.1
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SECRET_KEY: "django-insecure-dev-key"
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
      DATABASE_URL: "postgresql://neondb_owner:npg_vtIKcTmC8gN9@ep-dawn-mud-a1j09vq6-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      REDIS_URL: "redis://redis:6379"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      CORS_ALLOWED_ORIGINS: "http://192.168.1.101:8080,http://103.120.135.237:8080"
      CSRF_TRUSTED_ORIGINS: "http://192.168.1.101:8080,http://103.120.135.237:8080"

    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               daphne -b 0.0.0.0 -p 8000 factory_attendance.asgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_BASE: "http://103.120.135.237:8000/api"
      REACT_APP_WS_BASE: "ws://103.120.135.237:8000"
      WDS_SOCKET_PORT: "0"
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    volumes:
      - ./frontend:/app
