# Generated by Django 4.2.7 on 2026-03-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='stream_url',
            field=models.CharField(blank=True, default='', help_text='RTSP URL e.g. rtsp://user:pass@192.168.1.10:554/stream', max_length=500),
        ),
    ]
