# Generated by Django 4.2.7 on 2026-03-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_camera_stream_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('medical', 'Medical Leave'), ('emergency', 'Emergency'), ('unpaid', 'Unpaid Leave'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ot_start', models.DateTimeField()),
                ('ot_end', models.DateTimeField(blank=True, null=True)),
                ('ot_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ot_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_minutes', models.IntegerField(default=15)),
                ('is_overnight', models.BooleanField(default=False)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='late_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='attendance.employee'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='stream_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name_kh',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['timestamp'], name='attendance__timesta_01c0dc_idx'),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shift'),
        ),
        migrations.AlterUniqueTogether(
            name='overtimerecord',
            unique_together={('employee', 'date')},
        ),
    ]
