# Generated by Django 4.2.7 on 2026-03-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_faceembedding_leaverequest_overtimerecord_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='work_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='checkin_after',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='shift',
            name='checkin_before',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='shift',
            name='checkout_after',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='shift',
            name='checkout_before',
            field=models.IntegerField(default=30),
        ),
    ]
