# Generated by Django 4.2.7 on 2026-03-26 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancerecord_work_hours_shift_break_end_and_more'),
        ('attendance', '0004_camera_source_type_rtsp_fields'),
    ]

    operations = [
    ]
